config/routes.rb
Rails.application.routes.draw do
  get 'extras/new'

  devise_for :users

  root to: "listings#index"
  resources :listings do
    resources :bookings, only: [:new, :create, :index]
    resources :extras, only: [:new]
  end

  get "sellerlistings", to: "listings#sellerlistings", as: :seller_listings
  get "listingsbookings", to: "listings#listingsbookings", as: :listings_bookings
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :listing
  has_many :booking_extras
  attr_accessor :start_hour, :duration, :date

  validate :validate_booking_hours

   def validate_booking_hours
  if start_hour.nil? || duration.nil?
    return
  end

  if duration.to_i > 5
    errors.add(:duration, "You can only book for a maximum of 5 hours!")
  end

  start_hour_integer = start_hour.to_i
  duration_integer = duration.to_i

  valid_start_hours = (10..20).to_a
  valid_duration_values = (1..5).to_a

  start_hour_is_valid = valid_start_hours.include?(start_hour_integer)
  duration_is_valid = valid_duration_values.include?(duration_integer)

  if !start_hour_is_valid || !duration_is_valid
    return
  end

  if start_hour_integer +  duration_integer > 21
    errors.add(:base, "Booking must end no later than 21:00")
    end
  end

  def total_price
    listing.price_per_hour * duration.to_i
  end
end

app/models/booking_extra.rb
class BookingExtra < ApplicationRecord
  belongs_to :booking
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :bookings
  validates :spot_row, :spot_column, presence: true
  validates :spot_row, uniqueness: { scope: :spot_column }
  validates :spot_column, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 50 }
  validates :spot_row, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 4 }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :listings
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :role])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  def after_sign_up_path_for(resource)
    if resource.role == "Seller"
    seller_listings_path
    else
    listings_path
    end
  end

  def after_sign_in_path_for(resource)
    if resource.role == "Seller"
      seller_listings_path
    else
      listings_path
    end
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @listing = Listing.find(params[:listing_id])
    @booking = Booking.new
  end

  def index
    @bookings = current_user.bookings
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def create
  @listing = Listing.find(params[:listing_id])
  @booking = @listing.bookings.new(booking_params)
  @booking.price = @booking.total_price

  @selected_date = params[:date]

  selected_date = Date.parse(params[:booking][:date])

  selected_hour = params[:booking][:start_hour].to_i
  @booking.start_date = DateTime.new(selected_date.year, selected_date.month, selected_date.day, selected_hour, 0, 0)
  @booking.end_date = @booking.start_date + params[:booking][:duration].to_i.hours
  @booking.user_id = current_user.id

    if @booking.save
      @booking.update(status: "confirmed")
      redirect_to listing_bookings_path(@listing), notice: "Booking created!"
    else
      render :new
    end
  end

  def destroy
  Booking.destroy
  end

  private

  def set_listing
  @listing = Listing.find(params[:listing_id])
  end

  def booking_params
  params.require(:booking).permit(:date, :start_hour, :duration, :status, :listing_id, :user_id)
  end
end

app/controllers/extras_controller.rb
class ExtrasController < ApplicationController
  def new
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:date].present?
      @date = Date.parse(params[:date])
    else
      @date = Date.today
    end

    bookings_on_date = Booking.where("? BETWEEN DATE(start_date) AND DATE(end_date)", @date)

    booked_ids = bookings_on_date.map(&:listing_id)

    @listings = Listing.where.not(id: booked_ids)
  end

  def show
    @listing = Listing.find(params[:id])
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = current_user.listings.build(listing_params) # Associate the listing with the logged-in user
    if @listing.save
      redirect_to seller_listings_path, notice: "Listing was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def sellerlistings
    @listings = current_user.listings
    # Listing.all where Listing.user_id ==
  end

  def listingsbookings
    @listings = current_user.listings
    @bookings = Booking.where(listing_id: current_user.listing_ids)
    @listings_bookings = current_user.listings.joins(:bookings).distinct
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def update
    @listing = Listing.find(params[:id])
    if @listing.update(listing_params)
      redirect_to seller_listings_path, notice: "Listing successfully updated!"
    else
      flash[:alert] = "Error: Unable to update listing."
      render :edit
    end
  end

  private

  def listing_params
    params.require(:listing).permit(:description, :price_per_hour, :spot_column, :spot_row)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
#   def home
#   end

  def listings
  end

end
# We are not going to use home on this project

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div style="text-align: center;">
  <h2>Your bookings:</h2>
</div>

<% @bookings.each do |booking| %>
  <div class="text-center border border-primary rounded mt-4 mb-4 p-4">
    <div class="text-center p-2 mb-2">
      <%= image_tag "beach-img.jpg", alt: "An image of the spot on the beach", style: "width: 20%; height: auto;", class: "img-fluid custom-rounded w-80" %>
    </div>
      <%# <h3 class="mb-4">Description: <%= listing.description %></h3>
    <p class="p-2">Total price: $<%= booking.price %></p>
    <p>Booked <%= booking.start_date.strftime("%Y-%m-%d") %> from <%= booking.start_date.strftime("%H:%M") %> to <%= booking.end_date.strftime("%H:%M") %></p>
    <p>Status: <%= booking.status.capitalize %></p>
    <button id="pick-btn" class="btn px-5 py-3 rounded-pill" style="background:#F37515; color:white; border:none;">Cancel</button>
  </div>
<%end%>
<%= link_to "Book more", root_path, class: "primarybuttonblue" %>

app/views/bookings/new.html.erb
<%= simple_form_for [@listing, @booking] do |f| %>
  <%= f.input :date, as: :string, input_html: {type: "date", class: "form-control",min: Date.today, value: params[:date] || Date.today.strftime("%Y-%m-%d")} %>

  <%= f.input :start_hour, collection: ([Time.now.hour, 10].max..20).map { |h| ["#{h}:00", h] }, prompt: 'Select starting time for booking' %>

  <%= f.input :duration, collection: (1..5).map { |h| ["#{h} hour#{'s' if h > 1}", h] }, prompt: 'Select duration of booking' %>

  <%= f.button :submit, "Book spot", class: "primarybuttonblue" %>
<% end %>

app/views/extras/new.html.erb
<h1>Extras#new</h1>
<p>Find me in app/views/extras/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shorespot</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/listings/edit.html.erb
<h1>Edit Listing</h1>
<%# # Knows whether it is patch or post because it can tell wheter @listing already has an id assinged to it %>
<%= simple_form_for @listing do |f| %>
  <%= f.input :description %>
  <%= f.input :price_per_hour, label: "Price per hour ($)" %>
  <%= f.input :spot_column, label: "Column number" %>
  <%= f.input :spot_row, label: "Row number" %>

  <%= f.submit "Update Listing", class: "btn btn-primary" %>
<% end %>

<%= link_to "Cancel", listing_path(@listing), class: "mt-2 btn btn-secondary" %>

app/views/listings/index.html.erb
<div class="container py-2">
  <div class="row mb-3">
    <div class="col-12">
      <div class="p-3 bg-white rounded-3 shadow-sm mx-auto" style="width: 95%; max-width: 1000px;">
        <label for="date" class="form-label fw-semibold">Date from</label>
        <%= form_with url: listings_path, method: :get, local: true do %>
          <div class="d-flex gap-2 align-items-center">
            <input type="date" name="date" id="selected-date" class="form-control" value="<%= @date.strftime('%Y-%m-%d') %>">
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", () => {
    const dateInput = document.getElementById("selected-date")
    dateInput.addEventListener("change", () => {
      const newDate = dateInput.value
      window.location.href = `/listings?date=${newDate}`
    })
  })
</script>

<div class="umbrella-header text-center text-white py-3" style="background-image: url('<%= asset_path("ocean.jpg") %>'); background-size: cover; background-position: center;">
  <div class="fw-semibold fs-5">Welcome to ShoreSpot! </div>
  <div class="fs-6">Select your spot from the options below</div>
</div>

  <div class="umbrella-body" style= "background-color: #FFF6E3;"  data-controller="selection">
    <div class="umbrella-scroll-wrapper">
      <div id="umbrella-container" class="d-flex flex-column align-items-start">
        <% 4.times do |row| %>
          <div class="d-flex flex-row mb-2">
            <% 50.times do |col| %>
              <% spot = @listings.find { |l| l.spot_row == row + 1 && l.spot_column == col + 1 } %>
              <% reserved = spot.present? %>
              <% umbrella_class = reserved ? "bg-success" : "bg-secondary" %>
              <% selectable = reserved %>

              <div
                class="umbrella-box d-flex align-items-center justify-content-center me-1 mb-1 rounded-circle <%= umbrella_class %>"
                data-selectable="<%= selectable %>"
                data-row="<%= row + 1 %>"
                data-col="<%= col + 1 %>"
                data-action="click->selection#toggle"
                <% if reserved %>data-listing-id="<%= spot.id %>"<% end %>

                style="border: 2px solid #fff;">
                <%= image_tag 'umbrella.png', width: 15, height: 15, alt: 'umbrella' %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>

    <div id="selected-info" class="text-center fw-semibold mt-3 fs-5"></div>

    <div class="text-center mb-3">
      <%= link_to "Pick", "#", class: "secondarybuttonorange", data: { action: "click->selection#pick" } %>
    </div>

  </div>
</div>

<div class="text-center my-3">
  <% if user_signed_in? %>
  <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "btn primarybuttonblue" %>
  <% else %>
   <%= link_to "Log in", new_user_session_path, class: "primarybuttonblue" %>
  <% end %>
</div>

<div class="text-center my-4">
  <span class="text-muted fs-5 fw-medium">or </span>
 <%= link_to "Signup", new_user_registration_path, class: "text-decoration-none fs-5 fw-bold", style: "color: #F37515;" %>
</div>

app/views/listings/listingsbookings.html.erb
<h2 class="mb-4">Bookings for my listing</h2>

  <% @bookings.each do |booking| %>

<div class="text-center p-2 mb-2">
  <%= image_tag "beach-img.jpg", alt: "An image of the spot on the beach", class: "img-fluid custom-rounded w-80" %>
</div>

<div class="text-center border border-primary rounded mt-4 mb-4 p-4">
  <h3 class="mb-4">Booking Details:</h3>

  <p class="mb-4">
    <strong>Start Date & Time:</strong>
    <span class="fw-bold text-primary"><%= booking.start_date.strftime("%A, %d %b %Y at %I:%M %p") %></span>
  </p>

  <p class="mb-4">
    <strong>End Date & Time:</strong>
    <span class="fw-bold text-danger"><%= booking.end_date.strftime("%A, %d %b %Y at %I:%M %p") %></span>
  </p>

  <p class="mb-4">
    <strong>Status:</strong>
    <span class="text-decoration-underline"><%= booking.status.capitalize %></span>
  </p>

   <%= link_to "Back to all listings", seller_listings_path, class: "btn btn-primary" %>

</div>

  <% end %>

app/views/listings/new.html.erb
<%= simple_form_for @listing do |f| %>
  <%= f.input :description, as: :text, placeholder: "Enter a brief description..." %>
  <%= f.input :price_per_hour, label: "Price per Hour ($)", input_html: { type: :number, min: 0 }, placeholder: "Enter the price per hour..." %>
  <%= f.input :spot_column, label: "Spot Column", input_html: { type: :number, min: 0 }, placeholder: "Enter a number between 1 - 50" %>
  <%= f.input :spot_row, label: "Spot Row", input_html: { type: :number, min: 0 }, placeholder: "Enter a number between 1 - 4" %>
  <%= f.submit "Create Listing" %>
<% end %>

app/views/listings/sellerlistings.html.erb
<% if @listings.any? %>
  <h2>All my Listings:</h2>
  <% @listings.each do |listing| %>
  <div class="text-center p-2 mb-2">
    <%= image_tag "beach-img.jpg", alt: "An image of the spot on the beach", class: "img-fluid custom-rounded w-80" %>
  </div>

  <div class="text-center border border-primary rounded mt-4 mb-4 p-4">
    <h3 class="mb-4">Description: <%= listing.description %></h3>
    <h2 class="p-2">$<%= listing.price_per_hour %> per hour</h2>
    <%= link_to "Edit", edit_listing_path(listing), class: "btn btn-primary" %>
    <%= link_to "View bookings for this listing", listings_bookings_path(listing), class: "btn btn-primary" %>
  </div>
  <% end %>

  <%= link_to "Upload a Listing", new_listing_path, class: "primarybuttonblue" %>


  <% else %>
  <p class="alert alert-warning">You have not uploaded any listings yet. Please upload a listing to start scamming tourists!!</p>
  <%= link_to "Upload a Listing", new_listing_path, class: "primarybuttonblue" %>

<% end %>

app/views/listings/show.html.erb
<%# <div class="container py-2">
  <div class="row mb-3">
    <div class="col-12">
      <div class="p-3 bg-white rounded-3 shadow-sm mx-auto" style="width: 100%">
        <label for="date" class="form-label fw-semibold">Date</label>
        <input type="date" class="form-control" id="date" name="date">
      </div>
    </div>
  </div>
</div> %>


<div class="text-center p-2 mb-2">
  <%= image_tag "beach-img.jpg", alt: "An image of the spot on the beach", class: "img-fluid custom-rounded w-80" %>
</div>



<h2 class="p-2">$<%= @listing.price_per_hour %> per hour</h2>


<div class="text-center border border-primary rounded mt-4 p-4">
  <h3 class="mb-4"><%= @listing.description %></h3>
  <%= link_to "Book me", new_listing_booking_path(@listing, date: params[:date]), class: "primarybuttonblue" %>
</div>

app/views/pages/home.html.erb
<<<<<<< HEAD
=======
#<<<<<<< index
>>>>>>> master
<<<<<<< HEAD
=======
=======
<h1>This is a H1</h1>

<h2>This is a H2</h2>

<h3>This is a H3</h3>

<p>Body text</p>

<%= link_to "primarybutton", "#", class:"primarybuttonblue" %>
<%= link_to "secondarybuttonorange", "#", class: "secondarybuttonorange" %>
>>>>>>> master
>>>>>>> master

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm">
  <div class="container">
    <a class="navbar-brand d-flex align-items-center" href="/">
      <img src="<%= asset_path('logo_shorespot.png') %>" alt="ShoreSpot Logo" width="36" height="36" class="me-2 rounded">
      <span class="fw-bold fs-4" style="letter-spacing:2px;"><h1>ShoreSpot</h1></span>
    </a>
  </div>
</nav>



    <%# <div class="ms-auto"> %>
      <%# <% if user_signed_in? %>
        <%# <span class="fw-semibold text-primary"><%= current_user.username</span> %>
      <%# <% else %>
        <%# <a href="/login" class="btn btn-primary px-4 text-white rounded">Log in</a> %>
      <%# <% end %>
      <%# </div> %>